- title: This site
  description: This site is written against github pages using the built in jekyll support. The aim of it is to be a one stop for anything regarding me that has to do with Software Engineering or the Industry surrounding it.
  url: /
  githubUrl: https://github.com/Mcphylus12/mcphylus12.github.io
- title: Jekyll Slideshow
  imageUrl: /assets/BG.PNG
  description: A site written for github pages with the intention of being a simple launch pad for small businesses that dont want to do anything more than deliver some contact details and examples of previous work. It is a constant work in progress and things will be added at the request of anyone who would want to have it as a template. The idea came as I have some family members running small businesses and want to have an online presence.
  url: /JekyllShowcase/
  githubUrl: https://github.com/Mcphylus12/JekyllShowcase
            